FWFTI-30 | POC-futbin ready first iteration
InternshipFWF/MateiColdea-fwf-futbin-best11-poc pull request #1
Opened 2023-08-17 08:58 UTC by mateicoldea

2023-08-17 11:42 UTC, AlexandraPertea requested changes
1. Application layer files should be inside a subfolder named after the automated application. In your case, your Futbin workflows should be inside ApplicationLayer/Futbin folder.
2. Please make sure to have a test case for every workflow that contains arguments.
3. Don't you only need the player name? Why make DataTable? Maybe I'm missing something.

2023-08-17 11:42 UTC, AlexandraPertea commented on ServiceLayer/UserInput/GetUserInput.xaml
> +    <ui:InputDialog Options="{x:Null}" OptionsString="{x:Null}" DisplayName="Input Dialog - League" sap:VirtualizedContainerService.HintSize="388,246" sap2010:WorkflowViewState.IdRef="InputDialog_1"
Since you tell the user to choose the league & formation, it would be best if the input type would be multiple choice. Either store the values in Config or (the best solution) make flows that extract the values directly from Futbin.

2023-08-17 11:42 UTC, AlexandraPertea commented on ApplicationLayer/Futbin_AddPlayers.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="Futbin_AddPlayers" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
I see you have some unused variables. Please remove them:
![image](https://github.com/InternshipFWF/MateiColdea-fwf-futbin-best11-poc/assets/102737511/71eae803-677a-456a-837f-0aa93d64caa3)

2023-08-17 11:42 UTC, AlexandraPertea commented on ApplicationLayer/Futbin_AddPlayers.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="Futbin_AddPlayers" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
You have some unused arguments as well - please remove them:
![image](https://github.com/InternshipFWF/MateiColdea-fwf-futbin-best11-poc/assets/102737511/e9cfdad4-792d-417a-9048-24e203d49290)

2023-08-17 11:42 UTC, AlexandraPertea commented on DataLayer/ChooseName.xaml
> +                  <If Condition="[in_usedPlayers.Contains(out_Name.ToString) = false]" DisplayName="If Player Hasn't Been Used - Choose Name" sap:VirtualizedContainerService.HintSize="434,450" sap201
Instead of "_Condition_ = false", you could write something like "Not _Condition_"
![image](https://github.com/InternshipFWF/MateiColdea-fwf-futbin-best11-poc/assets/102737511/1f26e5cc-982b-4a7d-a7a2-88e50d615625)

2023-08-17 11:42 UTC, AlexandraPertea commented on DataLayer/CreatePositionsDict.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="CreatePositionsDt" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
Please make sure to remove this variable as well:
![image](https://github.com/InternshipFWF/MateiColdea-fwf-futbin-best11-poc/assets/102737511/a0857e95-e8a3-41e8-9812-7e04bee31517)

2023-08-17 11:42 UTC, AlexandraPertea commented on ApplicationLayer/Futbin_SaveSquad.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="Futbin_SaveSquad" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
You have an unused variable here as well:
![image](https://github.com/InternshipFWF/MateiColdea-fwf-futbin-best11-poc/assets/102737511/44af4c14-4f7c-4f52-9077-1fe6e89f31d0)

2023-08-17 11:42 UTC, AlexandraPertea commented on ApplicationLayer/Futbin_AddPlayers.xaml
> +    <ui:LogMessage DisplayName="Log Message" sap:VirtualizedContainerService.HintSize="606,144.66666666666666" sap2010:WorkflowViewState.IdRef="LogMessage_1" Message="[&quot;Adding Players...&quot;]"
Please rename this activity:
![image](https://github.com/InternshipFWF/MateiColdea-fwf-futbin-best11-poc/assets/102737511/97a79ad4-e110-475c-be1b-bac386512f08)

2023-08-17 11:42 UTC, AlexandraPertea commented on Main.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="Main" VisualBasic.Settings="{x:Null}" sap:VirtualizedContainerService.HintSize="586.6666666666666,1948.6666666666667" sap2010:WorkflowViewState.IdRef="Ac
You may have duplicate variables. When on the Main Sequence scope, I get this:
![image](https://github.com/InternshipFWF/MateiColdea-fwf-futbin-best11-poc/assets/102737511/ae2351d5-3603-4bc6-bc6f-2e23defeb923)
But if I move to the Robot Sequence - Main scope, I get this:
![image](https://github.com/InternshipFWF/MateiColdea-fwf-futbin-best11-poc/assets/102737511/f5dbc6ed-a742-419d-912d-34a4f1364588)

Make sure to remove them to no have any conflicts.

2023-08-17 12:09 UTC, mateicoldea commented on ApplicationLayer/Futbin_AddPlayers.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="Futbin_AddPlayers" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
All of them are used. Most of them passed as arguments for the invoked workflows

2023-08-17 13:41 UTC, AlexandraPertea commented on ApplicationLayer/Futbin_AddPlayers.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="Futbin_AddPlayers" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
Ok, it may be a bug on my Studio then.

2023-08-21 12:00 UTC, AlexandraPertea approved these changes
Great job!

2023-08-21 12:00 UTC, merged